version: '2'
services:
  client:
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'